### ISSUE TITLE
[Bug]: Janky scrolling on 0x animation speed

### ISSUE THREAD

**Issue by pc00per** [android/compose-samples#916] opened 2022-08-04 03:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

The scrolling is janky when we mess with Android's animation speed from dev options. Try turning all animations down to 0x & you'll still see that issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment] 2022-08-05 04:30
It isn't "janky" as it's not dropping frames. It's just not animated scrolling as animations are turned off so it snaps to its final destination. I am closing this as working as intended.

**Closed by bentrengrove** 2022-08-05 04:30 UTC
Labels: bug, triage me

**Comment by pc00per** [comment] 2022-08-05 05:57
> It isn't "janky" as it's not dropping frames. It's just not animated scrolling as animations are turned off so it snaps to its final destination. I am closing this as working as intended.

Okay. I've opened another issue to make scroll animation independent of animator_duration_scale. #920
