### ISSUE TITLE
[Jetsnack-Crash]：When I fast change home bottomNavItem then app happen crash 

### ISSUE THREAD

**Issue by qq451682583** [android/compose-samples#184] opened 2020-09-21 08:44 UTC
```
09-21 16:40:56.625  8118  8118 E AndroidRuntime: java.lang.IllegalArgumentException: LayoutNode@56c797f children: 0 measureBlocks: androidx.compose.ui.LayoutKt$measureBlocksOf$1@9041e9a is not ready. layoutState is NeedsRelayout
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.node.InnerPlaceable.draw(InnerPlaceable.kt:132)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.node.ModifiedLayoutNode.draw(ModifiedLayoutNode.kt:81)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.node.LayerWrapper$layer$1.invoke(Unknown Source:10)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.node.LayerWrapper$layer$1.invoke(Unknown Source:3)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.platform.RenderNodeLayer$updateDisplayList$1$1.invoke(RenderNodeLayer.kt:186)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.platform.RenderNodeLayer$updateDisplayList$1$1.invoke(Unknown Source:0)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1668)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:127)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.observeLayerModelReads(AndroidComposeView.kt:429)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.kt:185)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:474)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.draw(View.java:21654)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20511)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20469)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20469)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20469)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20469)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:20469)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3895)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3703)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2992)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:776)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8347)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-21 16:40:56.625  8118  8118 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by nickbutcher** [comment] 2020-09-21 12:04
Closing as dupe of #129

**Closed by nickbutcher** 2020-09-21 12:04 UTC
