### ISSUE TITLE
The project is using an incompatible version (4.2.0-alpha10) of the Android Gradle plugin.

### ISSUE THREAD

**Issue by RauanSatanbek** [android/compose-samples#208] opened 2020-10-01 05:09 UTC
The Upgrade Assistant failed to upgrade this project, finding no way of performing the Upgrade AGP version from 4.2.0-alpha10 to 4.2.0-alpha12 command, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc, or other unrecognized constructs, in Gradle build files).

Android Studio 4.2 Canary 12
Build #AI-202.6397.94.42.6847140, built on September 18, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8

**Comment by gastsail** [comment] 2020-10-02 15:19
Can you share your gradle file ? I think the problem is because your gradle-wrapper version differs from the gradle plugin version

**Comment by nickbutcher** [comment] 2020-10-02 16:12
I'm closing this issue as we've upgraded all samples to AGP `4.2.0-alpha13` in #212

**Closed by nickbutcher** 2020-10-02 16:12 UTC

**Comment by manmohan777** [comment] 2020-10-22 13:26
facing this same problem with  4.2.0-alpha13.

The Upgrade Assistant failed to upgrade this project, finding no way of performing the Upgrade AGP version from 4.2.0-alpha13 to 4.2.0-alpha14 command, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc, or other unrecognized constructs, in Gradle build files).

**Comment by montaguegabe** [comment] 2020-10-23 15:08
@manmohan777 

Doing a global find for "alpha13" and replacing it with "alpha14" resolved this issue for me. The OWL sample builds and runs, but none of the previews appear to work (with Android Studio 4.2 Canary 14)

**Comment by yeuchi** [comment] 2020-10-25 22:29
None of the Compose Preview projects work for me.  Not even the OWL sample.
Problem has persisted for a few months in the 4.2 Preview.

**Comment by cpednekar** [comment] 2021-06-03 03:36
> 
> 
> facing this same problem with 4.2.0-alpha13.
> 
> The Upgrade Assistant failed to upgrade this project, finding no way of performing the Upgrade AGP version from 4.2.0-alpha13 to 4.2.0-alpha14 command, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc, or other unrecognized constructs, in Gradle build files).

I had same issue where I was asked to upgrade from **7.0.0-beta01** to **7.0.0-beta03**.
I searched _Project Wide for 7.0.0-beta01_
Navigated to **com.example.compose.jetsurvey.buildsrc** and within that opened _**dependencies.kt**_
there was a dependency as **const val androidGradlePlugin = "com.android.tools.build:gradle:7.0.0-beta03"**
changed from **7.0.0-beta01** to **7.0.0-beta03** and it complied fine
