### ISSUE TITLE
TopAppBar title aligned bottom when system text font size is small

### ISSUE THREAD

**Issue by Veronikapj** [android/compose-samples#26] opened 2019-11-19 15:47 UTC
Device is Google pixel 3a, Os version is android 10.
System Setting > Display > font size is small 
Top App bar title looks bottom aligned.

![image](https://user-images.githubusercontent.com/360685/69161686-e36a0a00-0b2e-11ea-8a9c-e7d2adb1ce20.png)
![image](https://user-images.githubusercontent.com/360685/69161843-17452f80-0b2f-11ea-810a-d4580b5bc3ef.png)

**Comment by nickbutcher** [comment] 2019-11-22 14:56
Thank you for filing! However we consider this as working as intended. The Material spec specifies that Top App Bar titles should be bottom aligned (with the title's baseline 20dp from the bottom) so I'll close this as working as intended. Thanks again for the issue.

**Closed by nickbutcher** 2019-11-22 14:56 UTC
